### ISSUE TITLE
`immutables.Map` is not JSON Serializable

### ISSUE THREAD

**Issue by rowillia** [MagicStack/immutables#18]
```python
import json
import immutables
print(json.dumps(immutables.Map({'hello': 'world'})))
```

```
Traceback (most recent call last):
  File "test.py", line 3, in <module>
    print(json.dumps(immutables.Map({'hello': 'world'})))
  File "/opt/lyft/brew/Cellar/python36/3.6.5_1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/opt/lyft/brew/Cellar/python36/3.6.5_1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/opt/lyft/brew/Cellar/python36/3.6.5_1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/opt/lyft/brew/Cellar/python36/3.6.5_1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'Map' is not JSON serializable
```

**Comment by 1st1** [comment]
This I can't fix. Python's json module isn't very customizable, you need to handle that on your side with a custom encoder / the `default` argument to dumps: https://docs.python.org/3/library/json.html#json.dump

**Comment by elprans** [comment]
This actually seems like a genuine Python issue.  Why is `json.Encoder` hardcoded to `dict`?  There's not real reason why arbitrary `Mapping` instances can't be dumped.

**Comment by 1st1** [comment]
> Why is json.Encoder hardcoded to dict? 

@elprans I've no idea, I suggested that you should write a PEP to use singledispatch for JSON a couple of years ago :)
