### ISSUE TITLE
Tests test_none_collisions in CMapNoneTest and PyMapNoneTest fail on armv7l

### ISSUE THREAD

**Issue by mcepl** [MagicStack/immutables#53]
When building [the package for OpenSUSE](https://build.opensuse.org/package/show/devel:languages:python/python-immutables) on armv7l architecture, I get:

```
[  304s] ======================================================================
[  304s] FAIL: test_none_collisions (test_none_keys.CMapNoneTest)
[  304s] ----------------------------------------------------------------------
[  304s] Traceback (most recent call last):
[  304s]   File "/home/abuild/rpmbuild/BUILD/immutables-0.14/tests/test_none_keys.py", line 47, in test_none_collisions
[  304s]     self.assertEqual(map_mask(c_hash, j*5), idx)
[  304s] AssertionError: 13 != 12
[  304s] 
[  304s] ======================================================================
[  304s] FAIL: test_none_collisions (test_none_keys.PyMapNoneTest)
[  304s] ----------------------------------------------------------------------
[  304s] Traceback (most recent call last):
[  304s]   File "/home/abuild/rpmbuild/BUILD/immutables-0.14/tests/test_none_keys.py", line 47, in test_none_collisions
[  304s]     self.assertEqual(map_mask(c_hash, j*5), idx)
[  304s] AssertionError: 13 != 12
[  304s] 
[  304s] ----------------------------------------------------------------------
[  304s] Ran 152 tests in 98.443s
[  304s] 
[  304s] FAILED (failures=2)
```
[Full build log with all details](https://github.com/MagicStack/immutables/files/5652922/_log.txt)

**Comment by vstinner** [comment]
I guess that the tests are hardcoded for 64-bit systems, whereas armv7l is 32-bit.

**Comment by mcepl** [comment]
I think it may be worthy to mention this part of the build log:
```

[  190s] gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -Werror=return-type -g -DOPENSSL_LOAD_CONF -fwrapv -fno-semantic-interposition -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -Werror=return-type -g -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -Werror=return-type -g -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -Werror=return-type -flto=auto -g -fPIC -DNDEBUG=1 -I/usr/include/python3.8 -c immutables/_map.c -o build/temp.linux-armv7l-3.8/immutables/_map.o -O2 -std=c99 -fsigned-char -Wall -Wsign-compare -Wconversion
[  190s] In file included from /usr/include/python3.8/Python.h:8,
[  190s]                  from immutables/_map.h:5,
[  190s]                  from immutables/_map.c:2:
[  190s] /usr/include/python3.8/pyconfig.h:1597: warning: "_POSIX_C_SOURCE" redefined
[  190s]  1597 | #define _POSIX_C_SOURCE 200809L
[  190s]       | 
[  190s] In file included from /usr/include/bits/libc-header-start.h:33,
[  190s]                  from /usr/include/stdint.h:26,
[  190s]                  from /usr/lib/gcc/armv7hl-suse-linux-gnueabi/10/include/stdint.h:9,
[  190s]                  from immutables/_map.h:4,
[  190s]                  from immutables/_map.c:2:
[  190s] /usr/include/features.h:310: note: this is the location of the previous definition
[  190s]   310 | # define _POSIX_C_SOURCE 199506L
[  190s]       | 
[  190s] immutables/_map.c: In function ‘map_node_bitmap_assoc’:
[  190s] immutables/_map.c:905:62: warning: conversion to ‘Py_ssize_t’ {aka ‘int’} from ‘uint32_t’ {aka ‘unsigned int’} may change the sign of the result [-Wsign-conversion]
[  190s]   905 |             new_node = (MapNode_Array *)map_node_array_new(n + 1, mutid);
[  190s]       |                                                            ~~^~~
[  190s] immutables/_map.c:988:57: warning: conversion to ‘Py_ssize_t’ {aka ‘int’} from ‘uint32_t’ {aka ‘unsigned int’} may change the sign of the result [-Wsign-conversion]
[  190s]   988 |                 (MapNode_Bitmap *)map_node_bitmap_new(2 * (n + 1), mutid);
[  190s]       |                                                       ~~^~~~~~~~~
```

**Comment by elprans** [comment]
This seems to be an issue on all 32-bit arches.  See #50.
