### ISSUE TITLE
Cannot install on Windows-Python-2.7 due to: AttributeError: 'tuple' object has no attribute system

### ISSUE THREAD

**Issue by ankostis** [MagicStack/immutables#6]
On Windows & Python-2.7.10, pip-installing  fails with this:

```
> pip install immutables
Collecting immutables
  Downloading https://files.pythonhosted.org/packages/dc/22/e8c6a0b77657612b21f45519b3c08067793371e62bf027af84d49ac9d3e9/immutables-0.6.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "c:\users\joe\appdata\local\temp\pip-install-5psh9p\immutables\setup.py", line 7, in <module>
        if platform.uname().system != 'Windows':
    AttributeError: 'tuple' object has no attribute 'system'
```
Now, i noticed that in the project's classifiers it is written only python-3,
but `immutable` is actually fetched as a transitive dependency of `contextvars` *backported package*.

Anyhow, the problem is that:

- on Python 3, `platform.uname()` returns a class "like" a named-tuple:
  ```python
   >>> import platform
   >>> n = platform.uname(); n
    uname_result(system='Windows', node='hal', release='10', version='10.0.17134', machine='AMD64', processor='Intel64 Family 6 Model 69 Stepping 1, MonkeyIntel')
    >>> type(n).mro()
    [<class 'platform.uname_result'>, <class 'tuple'>, <class 'object'>]
  ```

- while on Python-2, it is a simple tuple:
  ```python
   >>> n
    ('Windows', 'hal', '8', '6.2.9200', 'AMD64', 'Intel64 Family 6 Model 69 Stepping 1, MonkeyIntel')
    >>> type(n)
    <type 'tuple'>
  ```

**Comment by ankostis** [comment]
But in general, isn't the `os.name == 'nt'` check not adequate for detecting Windows?

**Comment by elprans** [comment]
`contextvars` is a backport to Python 3.x (<3.7), it's not a Python 2 backport.

**Comment by 1st1** [comment]
Closing this one; we have no plans to support Python 2.7.
